#!/usr/bin/env python3
"""
Auto-caption dataset images using Florence-2 for LoRA training.

Replaces manual/placeholder captions with detailed, consistent descriptions
generated by Microsoft's Florence-2 vision model.

Usage:
    # Caption all images in a dataset directory
    python scripts/auto_caption.py /workspace/datasets/my_character --trigger "ohwx person"

    # Preview captions without overwriting existing ones
    python scripts/auto_caption.py /workspace/datasets/my_character --trigger "ohwx person" --preview

    # Force overwrite existing captions
    python scripts/auto_caption.py /workspace/datasets/my_character --trigger "ohwx person" --force

Requires: pip install transformers torch pillow
Florence-2-base (~0.5GB) runs comfortably on 8GB VRAM.
"""

import argparse
import sys
from pathlib import Path

IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".webp"}


def load_florence(device: str = "cuda"):
    """Load Florence-2 model and processor. Downloads on first run (~0.5GB)."""
    from transformers import AutoProcessor, AutoModelForCausalLM
    import torch

    model_id = "microsoft/Florence-2-base"
    print(f"  Loading {model_id}...")

    dtype = torch.float16 if device == "cuda" else torch.float32
    processor = AutoProcessor.from_pretrained(model_id, trust_remote_code=True)
    model = AutoModelForCausalLM.from_pretrained(
        model_id, trust_remote_code=True, torch_dtype=dtype
    ).to(device)
    model.eval()
    return model, processor


def caption_image(model, processor, image_path: str, device: str = "cuda") -> str:
    """Generate a detailed caption for a single image using Florence-2."""
    import torch
    from PIL import Image

    image = Image.open(image_path).convert("RGB")

    # <MORE_DETAILED_CAPTION> gives rich visual descriptions ideal for LoRA training
    task = "<MORE_DETAILED_CAPTION>"
    inputs = processor(text=task, images=image, return_tensors="pt").to(device)

    with torch.inference_mode():
        generated_ids = model.generate(
            input_ids=inputs["input_ids"],
            pixel_values=inputs["pixel_values"],
            max_new_tokens=256,
            num_beams=3,
        )

    result = processor.batch_decode(generated_ids, skip_special_tokens=False)[0]
    # Florence wraps output in task tags — extract the caption text
    caption = processor.post_process_generation(result, task=task, image_size=image.size)
    return caption.get(task, result).strip()


def format_caption(raw_caption: str, trigger: str, style_tags: str = "") -> str:
    """Format a raw Florence caption into LoRA training format.

    Output: "{trigger}, {cleaned_caption}, {style_tags}"
    """
    # Clean up common Florence artifacts
    caption = raw_caption.strip()
    # Remove leading "The image shows" / "This is" / "In the image" etc.
    for prefix in [
        "The image shows ", "The image depicts ", "This is an image of ",
        "This is a photo of ", "This is ", "In the image, ", "In this image, ",
        "The photo shows ", "The picture shows ",
    ]:
        if caption.lower().startswith(prefix.lower()):
            caption = caption[len(prefix):]
            break

    # Ensure starts with lowercase (natural continuation after trigger)
    if caption and caption[0].isupper():
        caption = caption[0].lower() + caption[1:]

    parts = [trigger, caption]
    if style_tags:
        parts.append(style_tags)

    return ", ".join(filter(None, parts))


def main():
    parser = argparse.ArgumentParser(
        description="Auto-caption dataset images using Florence-2 for LoRA training"
    )
    parser.add_argument("dataset_dir", help="Path to dataset directory containing images")
    parser.add_argument("--trigger", required=True, help="Trigger word to prepend (e.g. 'ohwx person')")
    parser.add_argument("--style", default="", help="Style tags to append (e.g. 'anime style, cel shaded')")
    parser.add_argument("--force", action="store_true", help="Overwrite existing captions")
    parser.add_argument("--preview", action="store_true", help="Print captions without saving")
    parser.add_argument("--device", default="cuda", choices=["cuda", "cpu"], help="Device (default: cuda)")

    args = parser.parse_args()
    dataset_dir = Path(args.dataset_dir)

    if not dataset_dir.is_dir():
        print(f"ERROR: {dataset_dir} is not a directory")
        sys.exit(1)

    # Find all images
    images = sorted(
        f for f in dataset_dir.iterdir()
        if f.suffix.lower() in IMAGE_EXTS
    )
    if not images:
        print(f"ERROR: No images found in {dataset_dir}")
        sys.exit(1)

    print(f"\n  Auto-captioning {len(images)} images in {dataset_dir}")
    print(f"  Trigger: {args.trigger}")
    if args.style:
        print(f"  Style tags: {args.style}")
    print()

    # Load model
    model, processor = load_florence(device=args.device)

    captioned = 0
    skipped = 0

    for img_path in images:
        txt_path = img_path.with_suffix(".txt")

        # Skip if caption exists and not forcing
        if txt_path.exists() and not args.force:
            existing = txt_path.read_text().strip()
            # Only skip if it looks like a real caption (not a placeholder)
            if "[" not in existing and len(existing) > 20:
                skipped += 1
                if args.preview:
                    print(f"  SKIP {img_path.name}: {existing[:80]}...")
                continue

        # Generate caption
        raw = caption_image(model, processor, str(img_path), device=args.device)
        formatted = format_caption(raw, args.trigger, args.style)

        if args.preview:
            print(f"  {img_path.name}:")
            print(f"    RAW: {raw}")
            print(f"    FMT: {formatted}")
            print()
        else:
            txt_path.write_text(formatted)
            print(f"  {img_path.name} → {formatted[:80]}...")

        captioned += 1

    print(f"\n  Done: {captioned} captioned, {skipped} skipped (existing)")
    if args.preview:
        print("  (preview mode — no files written)")


if __name__ == "__main__":
    main()
