#!/usr/bin/env python3
"""
Auto-caption dataset images using Florence-2 for LoRA training.

Replaces manual/placeholder captions with detailed, consistent descriptions
generated by Microsoft's Florence-2 vision model.

Usage:
    # Caption all images in a dataset directory
    python scripts/auto_caption.py /workspace/datasets/my_character --trigger "ohwx person"

    # Preview captions without overwriting existing ones
    python scripts/auto_caption.py /workspace/datasets/my_character --trigger "ohwx person" --preview

    # Force overwrite existing captions
    python scripts/auto_caption.py /workspace/datasets/my_character --trigger "ohwx person" --force

    # Character-aware: omit features the LoRA should learn
    python scripts/auto_caption.py /workspace/datasets/my_character --trigger "ohwx person" \
        --character-features "red hair, blue eyes, leather jacket, scar on left cheek"

    # Two-pass with Claude rewriting (best quality, requires ANTHROPIC_API_KEY)
    python scripts/auto_caption.py /workspace/datasets/my_character --trigger "ohwx person" \
        --character-features "red hair, blue eyes" --rewrite

Requires: pip install transformers torch pillow
Florence-2-base (~0.5GB) runs comfortably on 8GB VRAM.
"""

import argparse
import re
import sys
from pathlib import Path

IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".webp"}


def load_florence(device: str = "cuda"):
    """Load Florence-2 model and processor. Downloads on first run (~0.5GB)."""
    from transformers import AutoProcessor, AutoModelForCausalLM
    import torch

    model_id = "microsoft/Florence-2-base"
    print(f"  Loading {model_id}...")

    dtype = torch.float16 if device == "cuda" else torch.float32
    processor = AutoProcessor.from_pretrained(model_id, trust_remote_code=True)
    model = AutoModelForCausalLM.from_pretrained(
        model_id, trust_remote_code=True, torch_dtype=dtype
    ).to(device)
    model.eval()
    return model, processor


def caption_image(model, processor, image_path: str, device: str = "cuda") -> str:
    """Generate a detailed caption for a single image using Florence-2."""
    import torch
    from PIL import Image

    image = Image.open(image_path).convert("RGB")

    # <MORE_DETAILED_CAPTION> gives rich visual descriptions ideal for LoRA training
    task = "<MORE_DETAILED_CAPTION>"
    inputs = processor(text=task, images=image, return_tensors="pt").to(device)

    with torch.inference_mode():
        generated_ids = model.generate(
            input_ids=inputs["input_ids"],
            pixel_values=inputs["pixel_values"],
            max_new_tokens=256,
            num_beams=3,
        )

    result = processor.batch_decode(generated_ids, skip_special_tokens=False)[0]
    # Florence wraps output in task tags — extract the caption text
    caption = processor.post_process_generation(result, task=task, image_size=image.size)
    return caption.get(task, result).strip()


def strip_character_features(caption: str, features: list[str]) -> str:
    """Remove mentions of character-specific features from a caption.

    The LoRA should learn these features from the images themselves — describing
    them in the caption prevents the model from binding them to the trigger word.

    Args:
        caption: Raw or cleaned caption text.
        features: List of feature phrases to remove, e.g. ["red hair", "blue eyes"].

    Returns:
        Caption with feature mentions stripped and cleaned up.
    """
    for feature in features:
        feature = feature.strip()
        if not feature:
            continue
        # Case-insensitive removal of the feature phrase
        # Handle surrounding commas/conjunctions: "a person with red hair, wearing..."
        # Pattern: optional leading "with/and/,/ " + feature + optional trailing ", /and"
        patterns = [
            # "with red hair" / "and red hair" / ", red hair"
            rf",?\s*(?:with|and|featuring|has|having)?\s*{re.escape(feature)}",
            # Standalone mention
            rf"\b{re.escape(feature)}\b",
        ]
        for pat in patterns:
            caption = re.sub(pat, "", caption, flags=re.IGNORECASE)

    # Clean up leftover punctuation artifacts
    caption = re.sub(r",\s*,", ",", caption)       # double commas
    caption = re.sub(r"\.\s*,", ".", caption)       # period-comma
    caption = re.sub(r",\s*\.", ".", caption)       # comma-period
    caption = re.sub(r"\s{2,}", " ", caption)       # multiple spaces
    caption = re.sub(r"^\s*,\s*", "", caption)      # leading comma
    caption = re.sub(r",\s*$", "", caption)         # trailing comma
    return caption.strip()


def rewrite_caption_with_claude(
    raw_caption: str,
    trigger: str,
    character_features: list[str],
    style_tags: str = "",
) -> str:
    """Use Claude to rewrite a caption following LoRA training best practices.

    Two-pass approach:
    1. Florence-2 generates detailed raw caption (already done)
    2. Claude rewrites following rules: use trigger word, omit character features,
       describe background/environment in detail, specify camera/style.

    Requires ANTHROPIC_API_KEY environment variable.
    """
    import anthropic
    import os

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        raise RuntimeError("ANTHROPIC_API_KEY not set — cannot use --rewrite mode")

    client = anthropic.Anthropic(api_key=api_key)

    features_str = ", ".join(character_features) if character_features else "none specified"
    style_note = f"\n- Append these style tags at the end: {style_tags}" if style_tags else ""

    prompt = f"""Rewrite this image caption for LoRA training. Follow these rules strictly:

- Start with the trigger word: "{trigger}"
- DO NOT describe these character features (the LoRA learns them from images): {features_str}
- DO describe: pose, action, expression, body language, clothing details NOT in the feature list
- DO describe in detail: background, environment, lighting, colors, objects, atmosphere
- DO describe: camera angle, shot type, framing
- Keep it as one flowing sentence, no line breaks
- Be specific and visual — avoid vague words like "beautiful" or "nice"{style_note}

Raw caption from Florence-2:
{raw_caption}

Rewritten caption:"""

    response = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=300,
        messages=[{"role": "user", "content": prompt}],
    )
    return response.content[0].text.strip()


def format_caption(raw_caption: str, trigger: str, style_tags: str = "",
                   character_features: list[str] | None = None) -> str:
    """Format a raw Florence caption into LoRA training format.

    Output: "{trigger}, {cleaned_caption}, {style_tags}"

    If character_features is provided, strips those features from the caption
    so the LoRA can learn them from images rather than text.
    """
    # Clean up common Florence artifacts
    caption = raw_caption.strip()
    # Remove leading "The image shows" / "This is" / "In the image" etc.
    for prefix in [
        "The image shows ", "The image depicts ", "This is an image of ",
        "This is a photo of ", "This is ", "In the image, ", "In this image, ",
        "The photo shows ", "The picture shows ",
    ]:
        if caption.lower().startswith(prefix.lower()):
            caption = caption[len(prefix):]
            break

    # Strip character features if specified
    if character_features:
        caption = strip_character_features(caption, character_features)

    # Ensure starts with lowercase (natural continuation after trigger)
    if caption and caption[0].isupper():
        caption = caption[0].lower() + caption[1:]

    parts = [trigger, caption]
    if style_tags:
        parts.append(style_tags)

    return ", ".join(filter(None, parts))


def main():
    parser = argparse.ArgumentParser(
        description="Auto-caption dataset images using Florence-2 for LoRA training"
    )
    parser.add_argument("dataset_dir", help="Path to dataset directory containing images")
    parser.add_argument("--trigger", required=True, help="Trigger word to prepend (e.g. 'ohwx person')")
    parser.add_argument("--style", default="", help="Style tags to append (e.g. 'anime style, cel shaded')")
    parser.add_argument("--force", action="store_true", help="Overwrite existing captions")
    parser.add_argument("--preview", action="store_true", help="Print captions without saving")
    parser.add_argument("--device", default="cuda", choices=["cuda", "cpu"], help="Device (default: cuda)")
    parser.add_argument(
        "--character-features",
        default="",
        help="Comma-separated character features to OMIT from captions. "
             "These are visual traits the LoRA should learn from images, not text. "
             "E.g. 'red hair, blue eyes, leather jacket, scar on left cheek'"
    )
    parser.add_argument(
        "--rewrite",
        action="store_true",
        help="Two-pass mode: Florence-2 generates raw caption, then Claude rewrites "
             "following LoRA best practices. Requires ANTHROPIC_API_KEY. Uses claude-haiku-4-5 "
             "(fast + cheap). Best caption quality but slower."
    )

    args = parser.parse_args()
    dataset_dir = Path(args.dataset_dir)

    if not dataset_dir.is_dir():
        print(f"ERROR: {dataset_dir} is not a directory")
        sys.exit(1)

    # Parse character features
    char_features = [f.strip() for f in args.character_features.split(",") if f.strip()] if args.character_features else []

    # Find all images
    images = sorted(
        f for f in dataset_dir.iterdir()
        if f.suffix.lower() in IMAGE_EXTS
    )
    if not images:
        print(f"ERROR: No images found in {dataset_dir}")
        sys.exit(1)

    print(f"\n  Auto-captioning {len(images)} images in {dataset_dir}")
    print(f"  Trigger: {args.trigger}")
    if args.style:
        print(f"  Style tags: {args.style}")
    if char_features:
        print(f"  Character features to omit: {', '.join(char_features)}")
    if args.rewrite:
        print(f"  Two-pass mode: Florence-2 → Claude rewrite")
    print()

    # Load model
    model, processor = load_florence(device=args.device)

    captioned = 0
    skipped = 0

    for img_path in images:
        txt_path = img_path.with_suffix(".txt")

        # Skip if caption exists and not forcing
        if txt_path.exists() and not args.force:
            existing = txt_path.read_text().strip()
            # Only skip if it looks like a real caption (not a placeholder)
            if "[" not in existing and len(existing) > 20:
                skipped += 1
                if args.preview:
                    print(f"  SKIP {img_path.name}: {existing[:80]}...")
                continue

        # Generate caption
        raw = caption_image(model, processor, str(img_path), device=args.device)

        if args.rewrite:
            # Two-pass: Claude rewrites the Florence caption
            try:
                formatted = rewrite_caption_with_claude(raw, args.trigger, char_features, args.style)
            except Exception as e:
                print(f"  WARNING: Claude rewrite failed for {img_path.name}: {e}")
                print(f"           Falling back to local formatting")
                formatted = format_caption(raw, args.trigger, args.style, char_features)
        else:
            formatted = format_caption(raw, args.trigger, args.style, char_features)

        if args.preview:
            print(f"  {img_path.name}:")
            print(f"    RAW: {raw}")
            print(f"    FMT: {formatted}")
            print()
        else:
            txt_path.write_text(formatted)
            print(f"  {img_path.name} → {formatted[:80]}...")

        captioned += 1

    print(f"\n  Done: {captioned} captioned, {skipped} skipped (existing)")
    if args.preview:
        print("  (preview mode — no files written)")


if __name__ == "__main__":
    main()
